### PR TITLE
make relative dates translate-able

### PR DESCRIPTION
**Pull request by mapmeld**
first pass at updating angular-relative-date to work in the future and past, and solve the i18n question from #3:

- if the given date is ahead of the now-date, use terms like "4 hours from now" or  "tomorrow" in place of "4 hours ago" and "yesterday"
- use the angular-translate module to give users the option to translate the relative date. An interpolated translation is necessary because "4 hours ago" is not always ```"4 " + translate("hours_ago")``` it could be ```hace 4 horas```
- updated specs

### CODE REVIEW

**Comment by mapmeld** [comment]
@wildlyinaccurate would you be interested this as two separate pull requests?

**Comment by wildlyinaccurate** [comment]
Hey @mapmeld, sorry I didn't see this sooner! I think this is fine for a single PR. I'll have a look through it now. If you have time, could you write a few extra tests to check the angular-translate integration? No problem if not - I can do it :)

**Comment by wildlyinaccurate** [comment]
Hmm, I just realised that angular-translate is not a core Angular module. I wonder if there's a way to make this dependency optional - e.g. detect the angular-translate module, and fall back to English translations if not?

**Comment by wildlyinaccurate** [comment]
It's a little bit hacky, but I've taken what you had and made it so that this module doesn't require angular-translate to work: https://github.com/wildlyinaccurate/angular-relative-date/compare/mapmeld-translate-able

The only caveat is that to keep my translation polyfill simple, I made all of the interpolation parameters {{time}} instead of {{seconds}}, {{days}}, etc. Will this be a problem at all?

**Comment by mapmeld** [comment]
@wildlyinaccurate  that looks good!

**Comment by wildlyinaccurate** [comment]
Awesome, thanks for the PR! I'll tag a new version with these changes now.

**Pull request merged**
